# Identificación del proyecto en SonarQube
sonar.projectKey=TTRanking
sonar.projectName=TTRanking

# URL del servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de autenticación (pega el que acabas de crear)
sonar.token=sqp_9679f18e7ac9ec10cb9ee6bd6b7203a98f27c748

# Qué código analizar: "." = toda la carpeta del proyecto
sonar.sources=.

# Codificación
sonar.sourceEncoding=UTF-8
